[build]

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production]
  # Netlify automatically sets: CONTEXT, DEPLOY_PRIME_URL, URL
  
[context.deploy-preview]
  # Netlify automatically sets: CONTEXT, DEPLOY_PRIME_URL, REVIEW_ID

[context.branch-deploy]
  # Netlify automatically sets: CONTEXT, DEPLOY_PRIME_URL, BRANCH

[[redirects]]
from = "/"
to = "/docs"
status = 302

[[redirects]]
from = "/*"
to = "/docs/404.html"
status = 404

