version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Deps
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Yarn Build
          command: yarn build
  deployStaging:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli && aws --version
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Build site
          command: yarn build
      - run:
          name: Yarn Deploy Staging
          command: aws s3 sync build/ s3://staging-semgrep-dev/docs
  deployProd:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli && aws --version
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Build site
          command: yarn build
      - run:
          name: Yarn Prod Deploy
          command: aws s3 sync build/ s3://semgrep-docs/docs

workflows:
  build-and-deploy:
    jobs:
      - test
      - deployStaging:
          context:
            - aws
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - deployProd:
          context:
            - aws
          requires:
            - test
          filters:
            branches:
              only:
                - main
